### ISSUE TITLE
Special chars are replaced with HTML entities  in XLS (both 95+ and 2003+)

### ISSUE THREAD

**Issue by shum16** [kartik-v/yii2-export#126]
It seems like special chars are replaced with HTML entities in generated Excel reports. In my particular case I've got problem with ' " ' which is being replaced with '&quot;'. I'm using the latest version 1.2.4.

**Comment by shum16** [comment]
Is it possible to fix this?

**Comment by gael-wogenstahl** [comment]
Facing this issue too. Is this the expected behavior ?
Is it because data are HTML encoded when returned from dataProvider ?
Any workaround ?

**Comment by shum16** [comment]
Thanks a lot for the workaround with 'raw' format!

**Comment by gael-wogenstahl** [comment]
@kartik-v I can't find any way to fix that particular issue. Since `DataColumn` formatting should be used to render data the same way it would be rendered in a Grid there are no option to prevent HTML encoding unless tweaking the whole formatting system which is definitely not an option.
Do you have any idea ?

At least there is a workaround but data containing quotes and other special HTML characters aren't that rare and others might encounter the same problem.

**Comment by kartik-v** [comment]
This is more a PHPExcel library behavior. I will check if there is an option to enhance this.

**Comment by kartik-v** [comment]
This is more a Yii expected output format that PHPExcel library is directly displaying. 

You typically need to set the format only for the Export menu differently to avoid this.

**Comment by albel727** [comment]
No, it's because you always call `strip_tags()` (even with raw format, see #168), but don't also call `html_entity_decode()`. The fix should be trivial.

**Comment by kartik-v** [comment]
Will need to check this and update.

**Comment by KirillRyzhkov** [comment]
Hi Karik. Is it fixed now?

**Comment by cronfy** [comment]
Still an issue for me. Even with 'raw' format it strips html tags.
