### ISSUE TITLE
Is it possible to explicitly set Excel cells types?

### ISSUE THREAD

**Issue by null12** [kartik-v/yii2-export#39]
It throws the 'Class kartik\widgets\AssetBundle not found' exception. Could you please change the namespaces to 'use kartik\base\AssetBundle' for those who don't import the yii2-widgets module?

Also I have the following question. Currently in the generated Excel file all cells have the default Excel's 'general' format. In this case some big numbers are displayed in exponential form. Is it possible to somehow change those cells format to 'numeric' on exporting?

**Comment by kartik-v** [comment]
Dependency is fixed via latest update. For your other query on manipulating cell.. you can try using the onRenderDataCell event property to set the PHP excel cell format.

**Comment by null12** [comment]
Thanks for the advice, I'll try.

As for the dependencies, I still see kartik\ **widgets** \AssetBundle in ExportColumnAsset.php and ExportMenuAsset.php, it will still throw an exception. Or will these be fixed if I update via composer?

**Comment by kartik-v** [comment]
you need to update (yes via composer).

**Comment by ananthhh** [comment]
Its not fixed yet. All these below files have dependency to kartik\widgets\AssetBundle and not kartik\base\AssetBundle; Now i need to install all widgets just to use export. Its very annoying.
Check below lines
https://github.com/kartik-v/yii2-export/blob/master/ExportColumnAsset.php#L11
https://github.com/kartik-v/yii2-export/blob/master/ExportMenuAsset.php#L11

**Comment by kartik-v** [comment]
The above topic is not related to this issue subject. Create a separate issue for every separate fix or enhancement instead of combining. 

Your showing dissent OR flaming up is unwarranted NOR will I feel a need to respond. I am sharing these extensions at my own will and not governed/controlled by anyone or anything.

Note that I may not have time to address each of your personal needs or queries. It would do good if you have a fix or a suggestion - just submit a PR like you have done in #47. BTW - the PR is merged now.

**Comment by ananthhh** [comment]
I understand. I didn't meant to be so harsh. I am sorry about that. 
Thank you so much for sharing your hard work.

**Comment by infario** [comment]
I faced the same issue. I changed the class to 'use kartik\base\AssetBundle' which fixed the issue
